Feature session and private routing
wolox-training/ec-react pull request #6
Opened 2020-11-13 11:52 UTC by ema999

## Summary

Adding the react router featuring and Navbar component

## Screenshots

![Peek 2020-11-13 08-50](https://user-images.githubusercontent.com/26144389/99069587-64ff4700-258d-11eb-9ce8-ba62b0fa55e2.gif)

## Trello Card

https://trello.com/c/BPkcVTFN
https://trello.com/c/w4ypkKo4

2020-11-17 18:11 UTC, damfinkel requested changes

2020-11-17 18:11 UTC, damfinkel commented on src/components/NavBar/index.js
> +      <div>
ul

2020-11-17 18:11 UTC, damfinkel commented on src/components/NavBar/index.js
> +            <span
li

2020-11-17 18:11 UTC, damfinkel commented on src/components/NavBar/styles.module.scss
> +  flex-direction: row;
this is the default value, it's not necessary to explicityly set

2020-11-17 18:11 UTC, damfinkel commented on src/components/PrivateRoute/index.js
> +              pathname: '/login',
Define paths as constants somewhere, they'll probably be used somewhere else

2020-11-17 18:11 UTC, damfinkel commented on src/components/PublicRoute/index.js
> +import React from 'react';
This component and PrivateRoute are too similar. Can't we somehow reuse the code from both?

2020-11-17 18:11 UTC, damfinkel commented on src/components/PublicRoute/index.js
> +              pathname: '/',
constant

2020-11-18 20:11 UTC, damfinkel approved these changes

2020-11-18 20:46 UTC, DavidRojas1612 approved these changes

2020-11-18 20:49 UTC, merged