Feature book detail
wolox-training/ec-react pull request #8
Opened 2020-11-18 12:56 UTC by ema999

## Summary

I have created the screen to show the detail of the book when clicking on the list

## Screenshots

![book-detail](https://user-images.githubusercontent.com/26144389/99533183-3d8ced80-2984-11eb-97eb-0ea3841f214e.gif)

## Trello Card

https://trello.com/c/cQwagn0C

2020-11-19 15:53 UTC, DavidRojas1612 reviewed
Good Jod 🎉

2020-11-19 15:53 UTC, DavidRojas1612 commented on src/components/BookDetail/index.js
> +      <div className={clsx(styles.options, 'row', 'middle')}>
use clsx just to validate properties

2020-11-19 15:53 UTC, DavidRojas1612 commented on src/components/BookDetail/styles.module.scss
> +  box-shadow: 0 0 13px 0 rgba(50, 50, 50, 0.91);
use scss vatiables into rgba function like: 
`rgba($shadow, 0.91)`

2020-11-19 15:53 UTC, DavidRojas1612 commented on src/components/BookDetail/styles.module.scss
> +  padding-bottom: 20px;
use global classes m-bottom-x and p-bottom-x in your layout

2020-11-19 21:26 UTC, damfinkel requested changes

2020-11-19 21:26 UTC, damfinkel commented on src/screens/Books/index.js
> +function Books({ match }) {
I'd use `useParams`:
```
import { useParams } from "react-router-dom";
const { bookId } = useParams();
```

2020-11-19 21:26 UTC, damfinkel commented on src/screens/Books/index.js
> +    <BookDetailContext.Provider value={bookDetail}>
I wouldn't use Context here, I'd just do everything on the BookDetail component:

```
function BookDetail() {
  const [isLoading, submitError, response] = useRequest({
    request: getBookDetail,
    payload: match.params.bookId
  });

  return (
    <>
      {response?.ok && <p>{t('Errors:apiError')}</p>}}
      {isLoading && <p>{t('General:loadingContent')}...</p>}}
      {!isLoading && response.ok && (
        ...
      )}

    </>
  )
}
```

2020-11-20 13:00 UTC, damfinkel commented on src/components/BookDetail/index.js
> +      <div className={clsx(styles.options, 'row', 'middle')}>
I don't necessarily agree with this, I don't see much problem with using classnames here.

2020-11-20 16:21 UTC, DavidRojas1612 requested changes

2020-11-20 16:21 UTC, DavidRojas1612 commented on src/screens/BookDetail/index.js
> +          <div className={clsx(styles.book, 'row', 'space-around')}>
use clsx only to validate properties 
```suggestion
          <div className={` ${styles.book} row space-around`}>
```

2020-11-20 16:21 UTC, DavidRojas1612 commented on src/screens/BookDetail/index.js
> +            <div className={clsx(styles.description, 'column')}>
same

2020-11-20 16:21 UTC, DavidRojas1612 commented on src/screens/BookDetail/index.js
> +              <h1 className={clsx(styles.title, 'm-bottom-3')}>{book.title}</h1>
same

2020-11-20 16:21 UTC, DavidRojas1612 commented on src/screens/BookDetail/index.js
> +          <div className={clsx(styles.options, 'row', 'middle')}>
use clsx only to validate properties

2020-11-20 16:21 UTC, DavidRojas1612 commented on src/screens/BookDetail/styles.module.scss
> +  box-shadow: 0 0 13px 0 rgba(50, 50, 50, 0.91);
use scss variables insisde rgba functio 
```suggestion
  box-shadow: 0 0 13px 0 rgba($main-shadow, 0.91);
```

2020-11-20 16:44 UTC, damfinkel commented on src/screens/BookDetail/index.js
> +  const book = response && response.ok ? response.data : {};
remember that you can do `response?.ok` instead of `response && response.ok`

2020-11-20 16:44 UTC, damfinkel commented on src/screens/BookDetail/index.js
> +      {!isLoading && response && response.ok && (
same here

2020-11-20 16:44 UTC, damfinkel commented on src/screens/BookDetail/index.js
> +          <div className={clsx(styles.book, 'row', 'space-around')}>
I don't mind this

2020-11-20 17:07 UTC, DavidRojas1612 commented on src/screens/BookDetail/index.js
> +      {response && !response.ok && <p>{t('Errors:apiError')}</p>}
```suggestion
      {!response?.ok && <p>{t('Errors:apiError')}</p>}
```

2020-11-20 17:12 UTC, DavidRojas1612 approved these changes

2020-11-24 12:40 UTC, damfinkel approved these changes

2020-11-24 12:48 UTC, merged